# Generated by Django 5.1.6 on 2026-02-16 23:22

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre con el que se vende el medicamento (Ej: Ibuprofeno 600)', max_length=150, unique=True)),
                ('principio_activo', models.CharField(help_text='Sustancia química principal (Ej: Ibuprofeno, Paracetamol)', max_length=150)),
                ('concentracion', models.CharField(help_text='Concentración o cantidad (Ej: 600mg, 200ml, 10%)', max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('requiere_receta', models.BooleanField(default=False, help_text='Indica si se necesita receta médica para su venta.')),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'unique_together': {('nombre_comercial', 'concentracion')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado por farmacia'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='CARRITO', max_length=20)),
                ('detalles', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.CharField(blank=True, choices=[('SIN_STOCK', 'Sin stock'), ('RECETA_INVALIDA', 'Receta inválida'), ('FUERA_DE_COBERTURA', 'Fuera de cobertura'), ('PROBLEMAS_OPERATIVOS', 'Problemas operativos'), ('OTRO', 'Otro')], max_length=30, null=True)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
                ('codigo_seguridad', models.CharField(default=apps.orders.models.generar_codigo_numerico, help_text='Código de seguridad para entrega', max_length=6)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='accounts.cliente')),
                ('farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_farmacia', to='accounts.farmacia')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_repartidor', to='accounts.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receta_adjunta', models.FileField(blank=True, null=True, upload_to='recetas_pedidos/')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.medicamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='StockMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='accounts.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmacia_stock', to='orders.medicamento')),
            ],
            options={
                'verbose_name': 'Inventario de Medicamento',
                'verbose_name_plural': 'Inventario de Medicamentos',
                'unique_together': {('farmacia', 'medicamento')},
            },
        ),
    ]
