# Generated by Django 5.1.6 on 2026-02-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('documento', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('terms_cond', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cuit', models.CharField(default='00-00000000-0', max_length=13, unique=True)),
                ('cbu', models.CharField(default='000000000000000000000', max_length=22)),
                ('documentacion', models.FileField(null=True, upload_to='documentacion_farmacias/')),
                ('acepta_tyc', models.BooleanField(default=False)),
                ('valido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(default='00-00000000-0', max_length=13, unique=True)),
                ('cbu', models.CharField(default='000000000000000000000', max_length=22)),
                ('vehiculo', models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('patente', models.CharField(blank=True, max_length=7, null=True)),
                ('antecedentes', models.FileField(help_text='Documento de antecedentes (JPG, PNG o PDF).', upload_to='antecedentes_repartidores/')),
                ('disponible', models.BooleanField(default=True)),
                ('valido', models.BooleanField(default=False)),
            ],
        ),
    ]
