# Generated by Django 5.1.6 on 2026-07-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, help_text="EAN del producto o, si no tiene, 'vtex-<productId>'.", max_length=64, unique=True)),
                ('ean', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('vtex_product_id', models.CharField(max_length=32, unique=True)),
                ('product_reference', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('brand', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio efectivo por unidad aplicando la promo (ej: 50% la 2da unidad => 25% de descuento real).', max_digits=12, null=True)),
                ('promo_text', models.CharField(blank=True, default='', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='changomas.product')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='unique_price_per_day')],
            },
        ),
    ]
