# Generated by Django 5.1.6 on 2026-07-17 18:52

from django.db import migrations, models

GTIN_REGEX = r'^(\d{8}|\d{12}|\d{13}|\d{14})$'


def backfill_is_comparable(apps, schema_editor):
    """Marca los productos ya scrapeados cuyo EAN tiene largo GTIN válido."""
    Product = apps.get_model('changomas', 'Product')
    Product.objects.filter(ean__regex=GTIN_REGEX).update(is_comparable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('changomas', '0002_supermarkets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_comparable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_is_comparable, migrations.RunPython.noop),
    ]
