# Generated by Django 5.1.6 on 2026-02-16 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppFulbo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liga',
            name='presidentes',
            field=models.ManyToManyField(related_name='ligas_presididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liga',
            name='super_presidente',
            field=models.ForeignKey(blank=True, help_text='El super presidente de la liga, con privilegios especiales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligas_super_presididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugador',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='AppFulbo.liga'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partido',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='AppFulbo.liga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puntajepartido',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_partidos', to='AppFulbo.jugador'),
        ),
        migrations.AddField(
            model_name='puntajepartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_partidos', to='AppFulbo.partido'),
        ),
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_jugador', to='AppFulbo.jugador'),
        ),
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.liga'),
        ),
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.partido'),
        ),
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='puntaje_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.puntajepartido'),
        ),
        migrations.AddField(
            model_name='solicitudunionliga',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_union', to='AppFulbo.liga'),
        ),
        migrations.AddField(
            model_name='solicitudunionliga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_union', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together={('apodo', 'liga')},
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leido'], name='AppFulbo_no_usuario_63c084_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudunionliga',
            unique_together={('usuario', 'liga')},
        ),
    ]
