# Generated by Django 5.1.6 on 2025-03-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0026_rename_puntaje_puntajepartido_suma_puntajes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntajepartido',
            name='suma_puntajes',
        ),
        migrations.AddField(
            model_name='jugador',
            name='puntaje',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puntajepartido',
            name='puntaje',
            field=models.FloatField(null=True),
        ),
    ]
