# Generated by Django 5.1.6 on 2025-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0029_remove_mensaje_conversacion_remove_mensaje_remitente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='yo.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
