# Generated by Django 5.1.6 on 2025-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0030_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='apodo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
