# Generated by Django 5.1.6 on 2025-07-10 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0031_alter_jugador_apodo_alter_profile_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leido'], name='AppFulbo_no_usuario_63c084_idx'),
        ),
    ]
