# Generated by Django 5.1.6 on 2025-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0032_notificacion_appfulbo_no_usuario_63c084_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
